name: lint and test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      - name: Hatch static analysis
        run: |
          hatch run python -V
          hatch fmt --check
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Check scripts with shellcheck
        run: shellcheck scripts/*.sh

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext ffmpeg
          sudo ln -s /bin/true /bin/mpv
      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install ffmpeg -y --limit-output --no-progress
          "package main; func main() { }" | Out-File mpv.go
          go build mpv.go
          Copy-Item mpv.exe C:\ProgramData\chocolatey\bin\mpv.exe
      - name: Install dependencies on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install ffmpeg gettext mpv
      - name: Run stable tests with hatch
        run: |
          hatch test --include python --parallel -m "not flaky" -v
      - name: Run flaky tests with hatch
        run: |
          hatch test --include python --parallel -m "flaky" -v
        continue-on-error: true
