# Publish to PyPI when new release is created

name: Publish on PyPI

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
      - name: Hatch build
        run: hatch build
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/project/ytcc
    permissions:
      id-token: write
    needs:
      - build
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
